### ISSUE TITLE
Minor: Nav bar sizing on smaller screen

### ISSUE THREAD

**Issue by manyaj57** [info442-aut21/e-team#95] opened 2021-11-22 17:25 UTC
Description: Nav bar is not formatted to responsive sizing. The "add you org" and "sign up" buttons hang off the allocated nav bar space. 

Steps to Reproduce:
1. Open the app and view from any page
2. make the screen smaller
expected: nav bar to be formatted to responsive sizing (switch to hamburger menu, smaller text, etc) 
Actual: It breaks and the buttons are not in nav bar area 
Tested on ChromeVersion 96.0.4664.55 (Official Build) on MacOs Catalina

**Comment by Sneha-8** [comment] 2021-11-24 17:28
This is a duplicate of #91

**Closed** 2021-11-24 17:29 UTC
Labels: bug, duplicate

**Comment by cherimarie** [comment] 2021-12-06 17:04
For development purposes, I can see how this is a duplicate of #51 but for @manyaj57 's phase 7 grade, I'm not counting it as such.
